project_id = "qazycmfhcopyihnycbkb"

[functions.bl-search]
verify_jwt = true

[functions.strategy-credits]
verify_jwt = true

[functions.get-credits]
verify_jwt = true

[functions.enrich-buyer]
verify_jwt = true

[functions.generate-strategy]
verify_jwt = true
